source "https://rubygems.org"

ruby "3.0.6"

gem "rails", "~> 7.1.2"
gem "sprockets-rails"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem 'rack-cors'

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem 'rspec-rails'
end

group :development do
  gem "web-console"
  gem 'annotate'
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end
