name: HeyCater Menu CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'

      - name: Install packages
        run: yarn install --non-interactive
        working-directory: ./client

      - name: Run ESLint
        run: yarn run lint
        working-directory: ./client

      - name: Run UnitTest
        run: yarn run test:cv
        working-directory: ./client

      - name: Run BuildProject
        run: yarn run build
        working-directory: ./client
